# test_gamepad_constants.rb
require_relative '../build/lib/LiteRGSS'

puts "=== Test Gamepad Constants ==="

puts "BUTTON_LEFT_FACE_DOWN   = #{LiteRGSS::Gamepad::BUTTON_LEFT_FACE_DOWN}"
puts "BUTTON_LEFT_FACE_LEFT   = #{LiteRGSS::Gamepad::BUTTON_LEFT_FACE_LEFT}"
puts "BUTTON_LEFT_FACE_RIGHT  = #{LiteRGSS::Gamepad::BUTTON_LEFT_FACE_RIGHT}"
puts "BUTTON_LEFT_FACE_UP     = #{LiteRGSS::Gamepad::BUTTON_LEFT_FACE_UP}"
puts "BUTTON_LEFT_THUMB       = #{LiteRGSS::Gamepad::BUTTON_LEFT_THUMB}"
puts "BUTTON_LEFT_TRIGGER_1   = #{LiteRGSS::Gamepad::BUTTON_LEFT_TRIGGER_1}"
puts "BUTTON_LEFT_TRIGGER_2   = #{LiteRGSS::Gamepad::BUTTON_LEFT_TRIGGER_2}"
puts "BUTTON_MIDDLE           = #{LiteRGSS::Gamepad::BUTTON_MIDDLE}"
puts "BUTTON_MIDDLE_LEFT      = #{LiteRGSS::Gamepad::BUTTON_MIDDLE_LEFT}"
puts "BUTTON_MIDDLE_RIGHT     = #{LiteRGSS::Gamepad::BUTTON_MIDDLE_RIGHT}"
puts "BUTTON_RIGHT_FACE_DOWN  = #{LiteRGSS::Gamepad::BUTTON_RIGHT_FACE_DOWN}"
puts "BUTTON_RIGHT_FACE_LEFT  = #{LiteRGSS::Gamepad::BUTTON_RIGHT_FACE_LEFT}"
puts "BUTTON_RIGHT_FACE_RIGHT = #{LiteRGSS::Gamepad::BUTTON_RIGHT_FACE_RIGHT}"
puts "BUTTON_RIGHT_FACE_UP    = #{LiteRGSS::Gamepad::BUTTON_RIGHT_FACE_UP}"
puts "BUTTON_RIGHT_THUMB      = #{LiteRGSS::Gamepad::BUTTON_RIGHT_THUMB}"
puts "BUTTON_RIGHT_TRIGGER_1  = #{LiteRGSS::Gamepad::BUTTON_RIGHT_TRIGGER_1}"
puts "BUTTON_RIGHT_TRIGGER_2  = #{LiteRGSS::Gamepad::BUTTON_RIGHT_TRIGGER_2}"
puts "BUTTON_UNKNOWN          = #{LiteRGSS::Gamepad::BUTTON_UNKNOWN}"
puts "AXIS_LEFT_TRIGGER       = #{LiteRGSS::Gamepad::AXIS_LEFT_TRIGGER}"
puts "AXIS_LEFT_X             = #{LiteRGSS::Gamepad::AXIS_LEFT_X}"
puts "AXIS_LEFT_Y             = #{LiteRGSS::Gamepad::AXIS_LEFT_Y}"
puts "AXIS_RIGHT_TRIGGER      = #{LiteRGSS::Gamepad::AXIS_RIGHT_TRIGGER}"
puts "AXIS_RIGHT_X            = #{LiteRGSS::Gamepad::AXIS_RIGHT_X}"
puts "AXIS_RIGHT_Y            = #{LiteRGSS::Gamepad::AXIS_RIGHT_Y}"

puts "OK"